name: Deploy Docs

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docs
        run: nimble docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

      - name: Deploy artifact to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
